name: Build
on:
  push:
    tags:
      - 'v*'
jobs:
  create_release:
    name: Create release
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    runs-on: ubuntu-latest
    steps:
      - id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Create release
        uses: actions/create-release@v1
        with:
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
  build_windows:
    name: Build windows
    needs:
      - create_release
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install flutter
        run: |
          mkdir ~/Tools && cd $_
          git clone https://github.com/flutter/flutter.git
          ~/Tools/flutter/bin/flutter config --enable-windows-desktop
          ~/Tools/flutter/bin/flutter doctor
        shell: bash
      - name: Build windows
        run: |
          ~/Tools/flutter/bin/flutter packages get
          ~/Tools/flutter/bin/flutter build windows
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: .\build\windows\runner\Release
      - name: Create archive
        run: |
          Compress-Archive -DestinationPath .\Release.zip -Path .\build\windows\runner\Release
      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/upload-release-asset@v1
        with:
          asset_content_type: application/zip
          asset_name: windows.zip
          asset_path: .\Release.zip
          upload_url: ${{ needs.create_release.outputs.upload_url }}
